######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 20 14:14:40 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += lcdtime.h mainframe.h picture.h textarea.h
SOURCES += lcdtime.cpp \
           main.cpp \
           mainframe.cpp \
           picture.cpp \
           process_cmd.cpp \
           textarea.cpp
