######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 26 10:14:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib
QT += network

# Input
HEADERS += myform.h
SOURCES += main.cpp myform.cpp
